### PR TITLE
DHS-2: Adding Nationality page

### PR DESCRIPTION
**Pull request by sherrif10**
With this PR,  we had not suggested this however my idea about nationality page is to allow the user to be able to record the nationality of the patient, Forexample whether a patient is a National, Foregner or refugee, 
   i added three features to choose from nationality field and we can only use this as per now after merging this[ Pr here](https://github.com/digitalhealthcaresociety/openmrs-module-registrationapp/pull/1), then we can pull rebase upstream master and be able to view nationality page
   
cc @prapakaransp  @sharvanan

### CODE REVIEW

**Review by safeclinics — APPROVED** [review]
Good work. we didn't thought this one but good have this field.

**Comment by sherrif10** [comment]
Sure this is another good field that need to be implemented, Many EMR companies are implementing it so i thought we need it to . Can you merge this ticket and update the system, i dont want to be merging these tickets alone

**Review by HexEcho — APPROVED** [review]

**Comment by sherrif10** [comment]
Thanks @sharvanan  @safeclinics  for approving

**Comment by HexEcho** [comment]
@sherrif10 , 
When clicking on Register Patients,
https://safehands.appbank.digital/openmrs/registrationapp/registerPatient.page?appId=dhs.registrationapp.registerPatient

Getting below error in the demo app,
UI Framework Error
Root Error
java.lang.RuntimeException: Cannot find controller or view for fragment: field/nationality
	at org.openmrs.ui.framework.fragment.FragmentFactory.processThisFragment(FragmentFactory.java:185)
	at org.openmrs.ui.framework.fragment.FragmentFactory.process(FragmentFactory.java:124)

**Comment by sherrif10** [comment]
True that error is expected , we need to update our server with current updated registration app module, i had built the omod file and shared it in jfrog, so it need to be up to date and everything will work perfect

**Comment by sherrif10** [comment]
Am looking into it asap just a moment can you now try checking https://safehands.appbank.digital/openmrs/registrationapp/registerPatient.page?appId=dhs.registrationapp.registerPatient

**Pull request merged**
