### PR TITLE
DHS-3:Configuring idcard page with corresponding json uuid

### PR DESCRIPTION
**Pull request by sherrif10**
WHAT I DID, 
 Adding idcard page which will r be rendered as drop down page under id card field , Will provide the screen shot to comfirm
cc @prapakaransp  @sharvanan

### CODE REVIEW

**Comment by sherrif10** [comment]
this is something we want to achieve cc @prapakaransp @sharvanan 

tins

**Comment by sherrif10** [comment]
This is the same way we are going to inherit while adopting nationality function

**Comment by sherrif10** [comment]
This is how  i have been able to achieve them , i have tested this locally with screen shot to comfirm

TINS2

**Review by prapakaransp — APPROVED** [review]

**Comment by sherrif10** [comment]
@prapakaransp  thanks @sharvanan waiting for your review on this

**Comment by sherrif10** [comment]
Am merging this cc @sharvanan

**Pull request merged**
